%{ open Ast %}

%token LPAREN RPAREN LBRACE RBRACE LBRACKET RBRACKET MATRIX SEMI COMMA 
%token PLUS MINUS TIMES DIVIDE MOD MATMULT 
%token ASSIGN EQ NEQ NOT LT LEQ GT GEQ CONCAT
%token MATCH QMARK DONE CONT LOOP ANY TRUE PASS
%token NUM STRING FUNC SUB CONST INCLUDE POINT
%token EOF
%token <float>	LITFLOAT
%token <int>	LITINT
%token <string>	ID

%right	ASSIGN
%left	EQ NEQ
%left	LT LEQ GT GEQ
%left	PLUS MINUS CONCAT
%left	TIMES DIVIDE MOD MATMULT
%right	NOT
